# Generated by Django 4.2.23 on 2025-06-14 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_student_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('unm', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('prog', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='assesment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.student'),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
