# Generated by Django 4.2.23 on 2025-06-14 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_student_alter_assesment_student_delete_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesment',
            name='que',
        ),
        migrations.CreateModel(
            name='AssementAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=500)),
                ('scored', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.exam')),
            ],
        ),
    ]
