# Generated by Django 4.2.23 on 2025-06-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_assesment_que_assementanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='is_attempt',
            field=models.BooleanField(default=False),
        ),
    ]
